# SPDX-FileCopyrightText: 2025 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: GLWTPL

apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  type: ClusterIP
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: discovery
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: rlpx
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: json-rpc
    - port: 8546
      targetPort: 8546
      protocol: TCP
      name: ws
    - port: 8547
      targetPort: 8547
      protocol: TCP
      name: graphql
---
apiVersion: v1
kind: Service
metadata:
  name: bootstrap
spec:
  type: ClusterIP
  clusterIP: None
  ipFamilyPolicy: SingleStack
  publishNotReadyAddresses: true
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: discovery
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: rlpx
