# SPDX-FileCopyrightText: 2025 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: GLWTPL

apiVersion: v1
kind: ConfigMap
metadata:
  name: nodes

data:
  static-nodes.json: |-
    [
      "enode://85593d6a84d4d3a7c7d82e2fbf85e088eaabefec7b08a8721768d850a8db704046c7436640238b165b4f63d3881a1c64f6658b623406ec0acffec89730bde4ba@bootstrap-0.besu-qbft.svc.cluster.local:30303",
      "enode://04554cfc94737357822dfe329870f298a8870c064dd506c9d813cca8c947ef123632d71fb22fc9d4c304afb7d3d02fcaa7ec1a9382855051b492a3602d45eb50@bootstrap-1.besu-qbft.svc.cluster.local:30303",
      "enode://45b2c594593664da9ee411f00c6f0bc8b703fb510df31a99d6ba9cf8e9c1eb35a3f595d665045e7e08d1be3902f73c219e99d96b84aaddcc55af1a62a2e09c8d@bootstrap-2.besu-qbft.svc.cluster.local:30303",
      "enode://5d15a4d7e9da3927aa9f7ffb1fefb1ae5e7881f651ef69c4feeedab7ff68d51a6e44a01ba10c578aa0ff5c129341dd4332cc18dfb7116ace5d5cc02d1dec69b2@bootstrap-3.besu-qbft.svc.cluster.local:30303"
    ]

  config.toml: |-
    data-path = "/data"
    genesis-file = "/etc/genesis/genesis.json"
    node-private-key-file = "/secrets/key"
    static-nodes-file = "/etc/besu/static-nodes.json"

    profile = "ENTERPRISE"

    # P2P network
    p2p-enabled=true
    p2p-port=30303
    host-allowlist=["*"]
    discovery-enabled=false

    # JSON-RPC
    rpc-http-enabled=true
    rpc-http-port=8545
    rpc-http-api=["ETH","NET","QBFT"]
    rpc-http-cors-origins=["all"]

    # Metrics
    metrics-enabled=true
    metrics-host="0.0.0.0"
    metrics-port=9545
