# SPDX-FileCopyrightText: 2025 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: GLWTPL

labels:
  - pairs:
      app: tsnsrv
    includeSelectors: true

resources:
  - ./deployment.yaml

configMapGenerator:
  - name: nuke-old-ts
    files:
      - ./nuke-old-ts

generators:
  - ./secret-generator.yaml
