# SPDX-FileCopyrightText: 2025 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: GLWTPL

apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tailscale-auth
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./secret.sops.yaml
