# SPDX-FileCopyrightText: 2025 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: GLWTPL

namespace: besu-qbft

resources:
  - ./deployment.yaml
  - ./service.yaml

labels:
  - includeSelectors: true
    pairs:
      app: loadbalancer

configMapGenerator:
  - name: loadbalancer-config
    files:
      - ./config.yaml
