# SPDX-FileCopyrightText: 2025 Daniel Sampliner <samplinerD@gmail.com>
#
# SPDX-License-Identifier: GLWTPL

namespace: firefly 

resources:
  - ./configmap.yaml
  - ./namespace.yaml
  - ./statefulset.yaml
